# Generated by Django 5.1.3 on 2024-11-24 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_caso', models.CharField(max_length=50)),
                ('ubicacion', models.CharField(max_length=100)),
                ('fono', models.IntegerField()),
                ('desc_caso', models.TextField()),
            ],
        ),
    ]
